apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: docker-secret
  labels:
   app: docker-secret
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ubuntu-pod
  template:
    metadata:
      labels:
        app: ubuntu-pod
    spec:
      imagePullSecrets:
       - name: dockerhub
      containers:
      - name: ubuntu
        image: tatianamoraru/mybuntu1
