apiVersion: v1
data:
  mysql-credentials: TXlQQHNz
kind: Secret
metadata:
  creationTimestamp: "2020-02-09T22:12:20Z"
  name: mysql-credentials
  namespace: default
  resourceVersion: "5484570"
type: Opaque

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: wordpress-deployment
  name: wordpress-deployment
  namespace: default
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: wordpress-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: wordpress-deployment
    spec:
      containers:
      - image: wordpress
        name: wordpress-deployment

---

apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: mysql-rs
  name: mysql-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-credentials
              key: password

--- 

apiVersion: v1
kind: Service
metadata:
  labels:
    svc: wordpress-svc
  name: wordpress-svc
spec:
  selector:
    app: wordpress-lb-pod
  ports:
  - name: http
    nodePort: 31372
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
